name: Flask CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov # Ensure pytest is installed regardless of requirements.txt

    - name: Adjust PythonPath and Run tests
      run: |
        echo "PYTHONPATH=$PYTHONPATH:$(pwd)/flask-app" >> $GITHUB_ENV
        pytest

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
